spring:
  application:
    name: mail-service
  config:
    import: optional:configserver:http://localhost:8888/
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
auth:
  jwt:
    key:
      public: ${KBE_JWT_PUBLIC_KEY}
