spring:
  application:
    name: song-service
  config:
    import: optional:configserver:http://localhost:8888/
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
