spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jduesentrieb/kbe-config
          default-label: main
          username: s0566845@htw-berlin.de
          password: ca19c6d2f7aacccd6213b7ab48a9bdd3e03b41cf
          search-paths: config
server:
  port: 8888
